# Add prefix for Ctrl-a
set -g prefix2 C-a
bind C-a send-prefix -2

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Enable colors: https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux
# https://old.reddit.com/r/wsl2/comments/syihsf/windows_terminal_tmux_neovim_messed_up_colors/hz5r2g7/
set -g default-terminal "screen-256color"
if 'infocmp -x tmux-256color > /dev/null 2>&1' 'set -g default-terminal "tmux-256color"'

# Aggressive resizing for clients
setw -g aggressive-resize on

# Enable mouse mode
set -g mouse on

# Highlight active window
set -g window-status-current-style bg=red

# Powerline font
tmux_conf_theme_left_separator_main='\uE0B0'
tmux_conf_theme_left_separator_sub='\uE0B1'
tmux_conf_theme_right_separator_main='\uE0B2'
tmux_conf_theme_right_separator_sub='\uE0B3'
