#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# Add custom bin scripts to PATH
export PATH="~/.local/bin:$PATH"

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# Export truecolor COLORTERM; some programs utilize this instead of TERM
export COLORTERM=truecolor

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Determine OS and set color support accordingly
case "$(uname -s)" in
  Linux) 
    if [ -x /usr/bin/dircolors ]; then
        test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias ls='ls --color=auto'
    fi
    ;;
  Darwin) 
    # macOS uses BSD ls; use built-in color flags
    alias ls='ls -G'
    ;;
esac

alias grep='grep --color=auto'

# Alias definitions.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Preview file content using bat (https://github.com/sharkdp/bat)
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# Enable fzf key-bindings
if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/key-bindings.bash"
  source "$(fzf-share)/completion.bash"
fi

# Dracula FZF theme: https://draculatheme.com/fzf
export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'

# Enable custom personal key-bindings
if [ -f ~/.key_bindings ]; then
    source ~/.key_bindings
fi

# Set default editor to nvim
export EDITOR=nvim

# Enable syntax highlighting in less
# Requires installation of GNU highlight packages: see https://superuser.com/a/71593
export LESSOPEN="| ~/.local/bin/src-hilite-lesspipe.sh %s"
export LESS=' -R '

# Use bat for man pages - https://github.com/sharkdp/bat#man
# export MANPAGER="sh -c 'col -bx | bat -l man -p'"
# Use batman instead which strips out sed colors
eval "$(batman --export-env)"

# Check if we're in WSL2
if grep -qEi "(microsoft.*WSL2|WSL2.*microsoft)" /proc/version 2>/dev/null; then
    # Fix WSL2 CUDA: https://github.com/microsoft/WSL/issues/8587#issuecomment-1229170859
    export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

    # Add CUDA bin folder to path
    export PATH=/usr/local/cuda/bin:$PATH

    # Open new tabs in same dir on windows terminal: https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory#bash
    # Edited to deal with dangling semi-colon in original PROMPT_COMMAND
    if [[ -z $PROMPT_COMMAND && $PROMPT_COMMAND != *\;\  ]]; then
        PROMPT_COMMAND="$PROMPT_COMMAND; "
    fi
    PROMPT_COMMAND=$PROMPT_COMMAND'printf "\e]9;9;%s\e\\" "$(wslpath -w "$PWD")"'
fi

# Source completions from Nix installed packages
# https://github.com/nix-community/home-manager/issues/1871#issuecomment-852739277
for completion_script in ~/.nix-profile/share/bash-completion/completions/*
do
  source "${completion_script}"
done

# Use fish for interactive shell instead
case "$(uname -s)" in
  Linux)
    parent_shell=$(ps --no-header --pid=$PPID --format=comm 2>/dev/null)
    ;;
  Darwin)
    parent_shell=$(ps -o comm= -p "$PPID" 2>/dev/null)
    ;;
  *)
    parent_shell=""
    ;;
esac

if [[ $parent_shell != "fish" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]
then
    shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
    exec fish $LOGIN_OPTION
fi