# Change prefix to Ctrl-a
set-option -g prefix C-a

# Start window numbering at 1
set -g base-index 1

# Enable colors: https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux
# https://old.reddit.com/r/wsl2/comments/syihsf/windows_terminal_tmux_neovim_messed_up_colors/hz5r2g7/
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

# Aggressive resizing for clients
setw -g aggressive-resize on

# Enable mouse mode
set -g mouse on

# Highlight active window
set -g window-status-current-style bg=red
