# Replace prefix with Ctrl-Space
unbind C-b
set -g prefix2 C-Space
bind C-Space send-prefix -2

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Key-bindings
# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# Open new split panes in same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Enable colors: https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux
# https://old.reddit.com/r/wsl2/comments/syihsf/windows_terminal_tmux_neovim_messed_up_colors/hz5r2g7/
set -g default-terminal "screen-256color"
if 'infocmp -x tmux-256color > /dev/null 2>&1' 'set -g default-terminal "tmux-256color"'

# Aggressive resizing for clients
setw -g aggressive-resize on

# Enable term mode
set-option -sa terminal-overrides ",xterm*:Tc"

# Enable mouse mode
set -g mouse on

# Disable right-click menu
unbind -n MouseDown3Pane

# Powerline font
tmux_conf_theme_left_separator_main='\uE0B0'
tmux_conf_theme_left_separator_sub='\uE0B1'
tmux_conf_theme_right_separator_main='\uE0B2'
tmux_conf_theme_right_separator_sub='\uE0B3'

# Plugins
set -g @plugin "dracula/tmux"

# Set dracula plugins
set -g @dracula-plugins "git time"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
